apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: {{ kube_admin.ca_oneline }}
    server: {{ kube_admin.cluster_url }}
  name: {{ kube_admin.cluster }}
contexts:
- context:
    cluster: {{ kube_admin.cluster }}
    namespace: {{ users.name }}
    user: {{ users.name }}
  name: {{ users.name }}-context 
current-context: {{ users.name }}-context
kind: Config
preferences: {}
users:
- name: {{ users.name }}
  user:
    client-certificate: "{{ users.path }}/{{ users.name }}/{{ users.name }}.crt"
    client-key: "{{ users.path }}/{{ users.name }}/{{ users.name }}.key"