kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: {{ users.name }}
  name: {{ users.name }}-manager
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["deployments", "replicasets", "pods", "events", "services", "configmaps", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"] # You can also use ["*"]

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ users.name }}-manager-ro
rules:
- apiGroups: [""]
  resources: ["nodes", "namespaces", "deployments", "replicasets", "pods", "events", "services", "configmaps"]
  verbs: ["get", "list", "watch","create", "update"]
  